dist: focal # Ubuntu 20.04 LTS
language: ruby

cache:
  - apt
  - bundler
  - npm

rvm:
  - 2.7.1

env:
  global:
    - SERVICE_NAME=beta_project
    - ARG_COMPOSE_WAIT_VER=2.9.0
    - DB_VERSION=5.7.33
    - DB_PASSWORD=db_password

git:
  depth: 1

services:
  - docker

install:
  - bundle config set --local deployment 'true'
  - |
    BUNDLE_WITHOUT=production \
    BUNDLE_PATH=vendor/cache \
    bundler install --local

before_script:
  - |
    docker run --rm --detach \
      --env MYSQL_ROOT_PASSWORD=${DB_PASSWORD} \
      --network=host \
      mysql:${DB_VERSION}

  - |
    docker build . \
      --build-arg ARG_COMPOSE_WAIT_VER=${ARG_COMPOSE_WAIT_VER} \
      --tag ${SERVICE_NAME}/wait:${ARG_COMPOSE_WAIT_VER} \
      -f dockerfiles/Dockerfile.wait

  - |
    docker run --rm \
      --env WAIT_HOSTS=127.0.0.1:3306 \
      --network=host \
      ${SERVICE_NAME}/wait:${ARG_COMPOSE_WAIT_VER}

  - |
    CI=true \
      bin/rails db:setup

jobs:
  include:
    - stage: Application correctness
      script: |
        CI=true \
          bin/rails test:db
      name: Test suite
