dist: focal # Ubuntu 20.04 LTS

env:
  global:
    - ARG_COMPOSE_WAIT_VER=2.9.0
    - DB_VERSION=5.7.33
    - DB_PASSWORD=db_password
    - ARG_RUBYGEMS_VERSION=3.2.27
    - ARG_RUBY_VERSION=2.7.4
    - ARG_APP_PATH=src
    - APP_NAME=beta_project
    - VERSION=0.1.0

git:
  depth: 1

services:
  - docker

install: skip

before_script:
  - docker network create ${APP_NAME}-bridge-docker-network
  
  - |
    docker run --rm --detach \
    --name ${APP_NAME}-db \
      --env MYSQL_ROOT_PASSWORD=${DB_PASSWORD} \
      --network=${APP_NAME}-bridge-docker-network \
      mysql:${DB_VERSION}

  - |
    docker run --rm --detach \
    --name ${APP_NAME}-redis \
      --network=${APP_NAME}-bridge-docker-network \
      redis:latest
    
  - |
    docker build . \
      --build-arg ARG_COMPOSE_WAIT_VER=${ARG_COMPOSE_WAIT_VER} \
      --tag ${APP_NAME}/wait:${ARG_COMPOSE_WAIT_VER} \
      -f dockerfiles/Dockerfile-wait

  - |
    docker run --rm \
      --env WAIT_HOSTS=${APP_NAME}-db:3306,${APP_NAME}-redis:6379 \
      --network=${APP_NAME}-bridge-docker-network \
      ${APP_NAME}/wait:${ARG_COMPOSE_WAIT_VER}

  - |
      docker build \
      . \
      --build-arg ARG_RUBYGEMS_VERSION=${ARG_RUBYGEMS_VERSION} \
      --build-arg ARG_RUBY_VERSION=${ARG_RUBY_VERSION} \
      --build-arg ARG_APP_PATH=${ARG_APP_PATH} \
      --tag ${APP_NAME}/app-ci:${VERSION} \
      -f dockerfiles/Dockerfile-ci

  - |
    docker run \
    --name ${APP_NAME}-app-ci \
    --env DOCKER=true \
    --env CI=true \
    --env REDIS_URL=redis://${APP_NAME}-redis:6379/1 \
    --env DB_PASSWORD=${DB_PASSWORD} \
    --env DB_HOST=${APP_NAME}-db \
    --env RAILS_LOG_TO_STDOUT=true \
    --network ${APP_NAME}-bridge-docker-network \
    ${APP_NAME}/app-ci:${VERSION} bash -c "bin/rails db:setup"
	
  - docker container ls

  - docker exec ${APP_NAME}-app-ci bash -c "bin/rails db:version"

jobs:
  include:
    - stage: Application correctness
      script:
	  	- docker container ls
	  	- docker exec ${APP_NAME}-app-ci bash -c "bin/rails test:db"
      name: Test suite
