dist: focal # Ubuntu 20.04 LTS
language: ruby

cache:
  - apt
  - bundler
  - npm

rvm:
  - 2.7.4

env:
  global:
    - ARG_COMPOSE_WAIT_VER=2.9.0
    - DB_VERSION=5.7.33
    - DB_PASSWORD=db_password
    - ARG_RUBYGEMS_VERSION=3.2.27
    - ARG_RUBY_VERSION=2.7.4
    - ARG_APP_PATH=src
    - APP_NAME=beta_project
    - VERSION=0.1.0
	

git:
  depth: 1

services:
  - docker

before_script:
  - docker network create ${APP_NAME}-bridge-docker-network
  
  - |
    docker run --rm --detach \
      --env MYSQL_ROOT_PASSWORD=${DB_PASSWORD} \
      --network=${APP_NAME}-bridge-docker-network \
      mysql:${DB_VERSION}

  - |
    docker build . \
      --build-arg ARG_COMPOSE_WAIT_VER=${ARG_COMPOSE_WAIT_VER} \
      --tag ${APP_NAME}/wait:${ARG_COMPOSE_WAIT_VER} \
      -f dockerfiles/Dockerfile.wait

  - |
    docker run --rm \
      --env WAIT_HOSTS=127.0.0.1:3306 \
      --network=${APP_NAME}-bridge-docker-network \
      ${APP_NAME}/wait:${ARG_COMPOSE_WAIT_VER}

  - |
    CI=true \
      bin/rails db:setup

jobs:
  include:
    - stage: Application correctness
      script: |
        CI=true \
          bin/rails test:db
      name: Test suite
