ARG ARG_RUBY_VERSION

# "Debian GNU/Linux 10 (buster)"
FROM ruby:${ARG_RUBY_VERSION}

LABEL maintener='joel.azemar@gmail.com'
LABEL com.example.version="0.0.1-beta"
LABEL vendor="ACME Inc."
LABEL com.example.release-date="2021-12-29"

ENV LANG C.UTF-8

RUN apt-get update -qq && \
  apt-get install -y build-essential \
  libpq-dev \
  nodejs \
  npm \
  vim \
  curl \
  bash \
  tree \
  && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

ARG ARG_RUBYGEMS_VERSION
ARG ARG_BUNDLER_VERSION
ARG ARG_APP_PATH

ENV RUBYGEMS_VERSION ${ARG_RUBYGEMS_VERSION}
ENV BUNDLER_VERSION ${ARG_BUNDLER_VERSION}
ENV APP_PATH ${ARG_APP_PATH}

ENV BUNDLE_JOBS 8
ENV BUNDLE_RETRY 5
ENV BUNDLE_WITHOUT development:test
ENV BUNDLE_CACHE_ALL true
ENV RAILS_ENV production
ENV RACK_ENV production
ENV NODE_ENV production

WORKDIR /${APP_PATH}

COPY . /${APP_PATH}

RUN gem update --system ${RUBYGEMS_VERSION}
RUN gem install bundler -v ${BUNDLER_VERSION}

RUN bundle config set --local deployment 'true'
RUN bundler install

RUN npm install --global yarn

RUN yarn install --frozen-lockfile --non-interactive --production

RUN bin/rails assets:precompile --trace

RUN yarn cache clean

RUN rm -rf node_modules tmp/cache vendor/assets spec

CMD [ "echo", "CI Container [$RUBYGEMS_VERSION]" ]
