ARG ARG_RUBY_VERSION

# "Debian GNU/Linux 10 (buster)"
FROM ruby:${ARG_RUBY_VERSION}

ENV LANG C.UTF-8

RUN apt-get update -qq && \
  apt-get install -y build-essential \
  libpq-dev \
  nodejs \
  vim \
  curl \
  bash \
  tree \
  && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

ARG ARG_RUBYGEMS_VERSION
ARG ARG_APP_PATH

ENV RUBYGEMS_VERSION ${ARG_RUBYGEMS_VERSION}
ENV APP_PATH ${ARG_APP_PATH}

ENV BUNDLE_WITHOUT production
ENV BUNDLE_JOBS 3
ENV BUNDLE_RETRY 3

WORKDIR /${APP_PATH}

COPY . /${APP_PATH}

RUN gem update --system ${RUBYGEMS_VERSION}

RUN bundle config set --local deployment 'true'
RUN bundler install

CMD [ "echo", "CI Container [$RUBYGEMS_VERSION]" ]
